# file: noinspection YAMLSchemaValidation
version: "2"

linters:
  default: none

  enable:
    - bodyclose
    - dogsled
    - errcheck
    - funlen
    - gocyclo
    - unused
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - copyloopvar
    - staticcheck
    - unconvert
    - unparam

  settings:
    depguard:
      rules:
        logger:
          deny:
            # logging is allowed only by logutils.Log,
            - pkg: "github.com/sirupsen/logrus"
              desc: logging is allowed only by logutils.Log.
            - pkg: "github.com/pkg/errors"
              desc: Should be replaced by standard lib errors package.
            - pkg: "github.com/instana/testify"
              desc: It's a fork of github.com/stretchr/testify.
          files:
            # logrus is allowed to use only in logutils package.
            - "!**/pkg/logutils/**.go"
    dupl:
      threshold: 100
    funlen:
      lines: -1 # the number of lines (code and empty lines) is not a right metric and leads to code without an empty line or one-liner.
      statements: 100
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport # https://github.com/go-critic/go-critic/issues/845
        - ifElseChain
        - octalLiteral
        - whyNoLint
    gocyclo:
      min-complexity: 18
    godox:
      keywords:
        - FIXME
    mnd:
      # don't include the "operation" and "assign"
      checks:
        - argument
        - case
        - condition
        - return
      ignored-numbers:
        - '0'
        - '1'
        - '2'
        - '3'
      ignored-functions:
        - strings.SplitN
    govet:
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Fatalf
      enable:
        - nilness
        - shadow
    errorlint:
      asserts: false
    lll:
      line-length: 140
    misspell:
      locale: US
      ignore-rules:
        - "importas" # linter name
    nolintlint:
      allow-unused: false # report any unused nolint directives
      require-explanation: true # require an explanation for nolint directives
      require-specific: true # require nolint directives to be specific about which linter is being skipped
    revive:
      rules:
        - name: indent-error-flow
        - name: unexported-return
          disabled: true
        - name: unused-parameter
        - name: unused-receiver
