#file: noinspection YAMLSchemaValidation
linters-settings:
  lll:
    line-length: 140
  govet:
    shadow: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  gocyclo:
    min-complexity: 18
  maligned:
    suggest-new: true
  dupl:
    threshold: 200
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  gocritic:
    settings:
      hugeParam:
        sizeThreshold: 200
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ptrToRefParam
      - octalLiteral
      - wrapperFunc
      - whyNoLint
  funlen:
    lines: 155
    statements: 70

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - funlen
    - gocyclo
    - gofmt
    - goimports
    - unused
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - copyloopvar
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam

  # don't enable:
  # - gochecknoglobals
  # - gocognit
  # - godox
  # - maligned
  # - prealloc