PROTOC := protoc
PROTO_DIR := pkg/proto

.PHONY: all clean proto

all: proto

clean:
	rm -f $(PROTO_DIR)/*.pb.go

proto:
	$(PROTOC) \
		--go_out=. \
		--go_opt=paths=source_relative \
		--go-grpc_out=. \
		--go-grpc_opt=paths=source_relative \
		$(PROTO_DIR)/network.proto