// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: pkg/proto/expost.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuxData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhiVrf        []byte                 `protobuf:"bytes,1,opt,name=phi_vrf,json=phiVrf,proto3" json:"phi_vrf,omitempty"`
	PiVrf         []byte                 `protobuf:"bytes,2,opt,name=pi_vrf,json=piVrf,proto3" json:"pi_vrf,omitempty"`
	PhiVdf        []byte                 `protobuf:"bytes,3,opt,name=phi_vdf,json=phiVdf,proto3" json:"phi_vdf,omitempty"`
	PiVdf         []byte                 `protobuf:"bytes,4,opt,name=pi_vdf,json=piVdf,proto3" json:"pi_vdf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuxData) Reset() {
	*x = AuxData{}
	mi := &file_pkg_proto_expost_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuxData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuxData) ProtoMessage() {}

func (x *AuxData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_expost_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuxData.ProtoReflect.Descriptor instead.
func (*AuxData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_expost_proto_rawDescGZIP(), []int{0}
}

func (x *AuxData) GetPhiVrf() []byte {
	if x != nil {
		return x.PhiVrf
	}
	return nil
}

func (x *AuxData) GetPiVrf() []byte {
	if x != nil {
		return x.PiVrf
	}
	return nil
}

func (x *AuxData) GetPhiVdf() []byte {
	if x != nil {
		return x.PhiVdf
	}
	return nil
}

func (x *AuxData) GetPiVdf() []byte {
	if x != nil {
		return x.PiVdf
	}
	return nil
}

// ExPostMessage represents a single message in the ex‐post timestamp protocol.
type ExPostMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Round         uint32                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Vk            string                 `protobuf:"bytes,3,opt,name=vk,proto3" json:"vk,omitempty"`
	Challenge     string                 `protobuf:"bytes,4,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Aux           *AuxData               `protobuf:"bytes,5,opt,name=aux,proto3" json:"aux,omitempty"`
	SigmaParts    []string               `protobuf:"bytes,6,rep,name=sigma_parts,json=sigmaParts,proto3" json:"sigma_parts,omitempty"`
	Id            string                 `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExPostMessage) Reset() {
	*x = ExPostMessage{}
	mi := &file_pkg_proto_expost_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExPostMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExPostMessage) ProtoMessage() {}

func (x *ExPostMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_expost_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExPostMessage.ProtoReflect.Descriptor instead.
func (*ExPostMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_expost_proto_rawDescGZIP(), []int{1}
}

func (x *ExPostMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExPostMessage) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *ExPostMessage) GetVk() string {
	if x != nil {
		return x.Vk
	}
	return ""
}

func (x *ExPostMessage) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *ExPostMessage) GetAux() *AuxData {
	if x != nil {
		return x.Aux
	}
	return nil
}

func (x *ExPostMessage) GetSigmaParts() []string {
	if x != nil {
		return x.SigmaParts
	}
	return nil
}

func (x *ExPostMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_pkg_proto_expost_proto protoreflect.FileDescriptor

const file_pkg_proto_expost_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/proto/expost.proto\x12\x05proto\"i\n" +
	"\aAuxData\x12\x17\n" +
	"\aphi_vrf\x18\x01 \x01(\fR\x06phiVrf\x12\x15\n" +
	"\x06pi_vrf\x18\x02 \x01(\fR\x05piVrf\x12\x17\n" +
	"\aphi_vdf\x18\x03 \x01(\fR\x06phiVdf\x12\x15\n" +
	"\x06pi_vdf\x18\x04 \x01(\fR\x05piVdf\"\xc5\x01\n" +
	"\rExPostMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05round\x18\x02 \x01(\rR\x05round\x12\x0e\n" +
	"\x02vk\x18\x03 \x01(\tR\x02vk\x12\x1c\n" +
	"\tchallenge\x18\x04 \x01(\tR\tchallenge\x12 \n" +
	"\x03aux\x18\x05 \x01(\v2\x0e.proto.AuxDataR\x03aux\x12\x1f\n" +
	"\vsigma_parts\x18\x06 \x03(\tR\n" +
	"sigmaParts\x12\x0e\n" +
	"\x02id\x18\a \x01(\tR\x02idB\x0eZ\fexpost/protob\x06proto3"

var (
	file_pkg_proto_expost_proto_rawDescOnce sync.Once
	file_pkg_proto_expost_proto_rawDescData []byte
)

func file_pkg_proto_expost_proto_rawDescGZIP() []byte {
	file_pkg_proto_expost_proto_rawDescOnce.Do(func() {
		file_pkg_proto_expost_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_expost_proto_rawDesc), len(file_pkg_proto_expost_proto_rawDesc)))
	})
	return file_pkg_proto_expost_proto_rawDescData
}

var file_pkg_proto_expost_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_expost_proto_goTypes = []any{
	(*AuxData)(nil),       // 0: proto.AuxData
	(*ExPostMessage)(nil), // 1: proto.ExPostMessage
}
var file_pkg_proto_expost_proto_depIdxs = []int32{
	0, // 0: proto.ExPostMessage.aux:type_name -> proto.AuxData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_expost_proto_init() }
func file_pkg_proto_expost_proto_init() {
	if File_pkg_proto_expost_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_expost_proto_rawDesc), len(file_pkg_proto_expost_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_expost_proto_goTypes,
		DependencyIndexes: file_pkg_proto_expost_proto_depIdxs,
		MessageInfos:      file_pkg_proto_expost_proto_msgTypes,
	}.Build()
	File_pkg_proto_expost_proto = out.File
	file_pkg_proto_expost_proto_goTypes = nil
	file_pkg_proto_expost_proto_depIdxs = nil
}
