// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: expost.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuxData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhiVrf        []byte                 `protobuf:"bytes,1,opt,name=phi_vrf,json=phiVrf,proto3" json:"phi_vrf,omitempty"`
	PiVrf         []byte                 `protobuf:"bytes,2,opt,name=pi_vrf,json=piVrf,proto3" json:"pi_vrf,omitempty"`
	PhiVdf        []byte                 `protobuf:"bytes,3,opt,name=phi_vdf,json=phiVdf,proto3" json:"phi_vdf,omitempty"`
	PiVdf         []byte                 `protobuf:"bytes,4,opt,name=pi_vdf,json=piVdf,proto3" json:"pi_vdf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuxData) Reset() {
	*x = AuxData{}
	mi := &file_expost_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuxData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuxData) ProtoMessage() {}

func (x *AuxData) ProtoReflect() protoreflect.Message {
	mi := &file_expost_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuxData.ProtoReflect.Descriptor instead.
func (*AuxData) Descriptor() ([]byte, []int) {
	return file_expost_proto_rawDescGZIP(), []int{0}
}

func (x *AuxData) GetPhiVrf() []byte {
	if x != nil {
		return x.PhiVrf
	}
	return nil
}

func (x *AuxData) GetPiVrf() []byte {
	if x != nil {
		return x.PiVrf
	}
	return nil
}

func (x *AuxData) GetPhiVdf() []byte {
	if x != nil {
		return x.PhiVdf
	}
	return nil
}

func (x *AuxData) GetPiVdf() []byte {
	if x != nil {
		return x.PiVdf
	}
	return nil
}

// ExPostMessage represents a single message in the ex‐post timestamp protocol.
type ExPostMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Round         uint32                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Vk            string                 `protobuf:"bytes,3,opt,name=vk,proto3" json:"vk,omitempty"`
	Challenge     string                 `protobuf:"bytes,4,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Aux           *AuxData               `protobuf:"bytes,5,opt,name=aux,proto3" json:"aux,omitempty"`
	SigmaParts    []string               `protobuf:"bytes,6,rep,name=sigma_parts,json=sigmaParts,proto3" json:"sigma_parts,omitempty"`
	From          string                 `protobuf:"bytes,7,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExPostMessage) Reset() {
	*x = ExPostMessage{}
	mi := &file_expost_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExPostMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExPostMessage) ProtoMessage() {}

func (x *ExPostMessage) ProtoReflect() protoreflect.Message {
	mi := &file_expost_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExPostMessage.ProtoReflect.Descriptor instead.
func (*ExPostMessage) Descriptor() ([]byte, []int) {
	return file_expost_proto_rawDescGZIP(), []int{1}
}

func (x *ExPostMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExPostMessage) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *ExPostMessage) GetVk() string {
	if x != nil {
		return x.Vk
	}
	return ""
}

func (x *ExPostMessage) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *ExPostMessage) GetAux() *AuxData {
	if x != nil {
		return x.Aux
	}
	return nil
}

func (x *ExPostMessage) GetSigmaParts() []string {
	if x != nil {
		return x.SigmaParts
	}
	return nil
}

func (x *ExPostMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

var File_expost_proto protoreflect.FileDescriptor

var file_expost_proto_rawDesc = string([]byte{
	0x0a, 0x0c, 0x65, 0x78, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x69, 0x0a, 0x07, 0x41, 0x75, 0x78, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x17, 0x0a, 0x07, 0x70, 0x68, 0x69, 0x5f, 0x76, 0x72, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x70, 0x68, 0x69, 0x56, 0x72, 0x66, 0x12, 0x15, 0x0a, 0x06, 0x70, 0x69, 0x5f,
	0x76, 0x72, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x70, 0x69, 0x56, 0x72, 0x66,
	0x12, 0x17, 0x0a, 0x07, 0x70, 0x68, 0x69, 0x5f, 0x76, 0x64, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x70, 0x68, 0x69, 0x56, 0x64, 0x66, 0x12, 0x15, 0x0a, 0x06, 0x70, 0x69, 0x5f,
	0x76, 0x64, 0x66, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x70, 0x69, 0x56, 0x64, 0x66,
	0x22, 0xc9, 0x01, 0x0a, 0x0d, 0x45, 0x78, 0x50, 0x6f, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x6b, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x76, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6c, 0x6c,
	0x65, 0x6e, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6c,
	0x6c, 0x65, 0x6e, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x03, 0x61, 0x75, 0x78, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x75, 0x78, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x03, 0x61, 0x75, 0x78, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x69, 0x67, 0x6d, 0x61,
	0x5f, 0x70, 0x61, 0x72, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x69,
	0x67, 0x6d, 0x61, 0x50, 0x61, 0x72, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x42, 0x0e, 0x5a, 0x0c,
	0x65, 0x78, 0x70, 0x6f, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_expost_proto_rawDescOnce sync.Once
	file_expost_proto_rawDescData []byte
)

func file_expost_proto_rawDescGZIP() []byte {
	file_expost_proto_rawDescOnce.Do(func() {
		file_expost_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_expost_proto_rawDesc), len(file_expost_proto_rawDesc)))
	})
	return file_expost_proto_rawDescData
}

var file_expost_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_expost_proto_goTypes = []any{
	(*AuxData)(nil),       // 0: proto.AuxData
	(*ExPostMessage)(nil), // 1: proto.ExPostMessage
}
var file_expost_proto_depIdxs = []int32{
	0, // 0: proto.ExPostMessage.aux:type_name -> proto.AuxData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_expost_proto_init() }
func file_expost_proto_init() {
	if File_expost_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_expost_proto_rawDesc), len(file_expost_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_expost_proto_goTypes,
		DependencyIndexes: file_expost_proto_depIdxs,
		MessageInfos:      file_expost_proto_msgTypes,
	}.Build()
	File_expost_proto = out.File
	file_expost_proto_goTypes = nil
	file_expost_proto_depIdxs = nil
}
