// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: mdag.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MDAGMessage represents a single message in the MDAG protocol
type MDAGMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the protocol session
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Round number starting from 0
	Round uint32 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	// The node's label for this round
	Label string `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	// Identity of the sending node
	From          string `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MDAGMessage) Reset() {
	*x = MDAGMessage{}
	mi := &file_mdag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MDAGMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MDAGMessage) ProtoMessage() {}

func (x *MDAGMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mdag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MDAGMessage.ProtoReflect.Descriptor instead.
func (*MDAGMessage) Descriptor() ([]byte, []int) {
	return file_mdag_proto_rawDescGZIP(), []int{0}
}

func (x *MDAGMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MDAGMessage) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *MDAGMessage) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *MDAGMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

var File_mdag_proto protoreflect.FileDescriptor

var file_mdag_proto_rawDesc = string([]byte{
	0x0a, 0x0a, 0x6d, 0x64, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x6c, 0x0a, 0x0b, 0x4d, 0x44, 0x41, 0x47, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f,
	0x6d, 0x42, 0x0c, 0x5a, 0x0a, 0x6d, 0x64, 0x61, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_mdag_proto_rawDescOnce sync.Once
	file_mdag_proto_rawDescData []byte
)

func file_mdag_proto_rawDescGZIP() []byte {
	file_mdag_proto_rawDescOnce.Do(func() {
		file_mdag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mdag_proto_rawDesc), len(file_mdag_proto_rawDesc)))
	})
	return file_mdag_proto_rawDescData
}

var file_mdag_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mdag_proto_goTypes = []any{
	(*MDAGMessage)(nil), // 0: proto.MDAGMessage
}
var file_mdag_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mdag_proto_init() }
func file_mdag_proto_init() {
	if File_mdag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mdag_proto_rawDesc), len(file_mdag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mdag_proto_goTypes,
		DependencyIndexes: file_mdag_proto_depIdxs,
		MessageInfos:      file_mdag_proto_msgTypes,
	}.Build()
	File_mdag_proto = out.File
	file_mdag_proto_goTypes = nil
	file_mdag_proto_depIdxs = nil
}
