// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pkg/proto/network.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// shared between all requests
	ClientVersion string `protobuf:"bytes,1,opt,name=clientVersion,proto3" json:"clientVersion,omitempty"` // client version
	Timestamp     int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`        // unix time
	Id            string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`                       // allows requesters to use request data when processing a response
	Gossip        bool   `protobuf:"varint,4,opt,name=gossip,proto3" json:"gossip,omitempty"`              // true to have receiver peer gossip the message to neighbors
	NodeId        string `protobuf:"bytes,5,opt,name=nodeId,proto3" json:"nodeId,omitempty"`               // id of node that created the message (not the peer that may have sent it). =base58(multihash(nodePubKey))
	NodePubKey    []byte `protobuf:"bytes,6,opt,name=nodePubKey,proto3" json:"nodePubKey,omitempty"`       // Authoring node Secp256k1 public key (32bytes) - protobufs serialized
	Sign          []byte `protobuf:"bytes,7,opt,name=sign,proto3" json:"sign,omitempty"`                   // signature of message data + method specific data by message authoring node.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageData) Reset() {
	*x = MessageData{}
	mi := &file_pkg_proto_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageData) ProtoMessage() {}

func (x *MessageData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageData.ProtoReflect.Descriptor instead.
func (*MessageData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_network_proto_rawDescGZIP(), []int{0}
}

func (x *MessageData) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *MessageData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessageData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageData) GetGossip() bool {
	if x != nil {
		return x.Gossip
	}
	return false
}

func (x *MessageData) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MessageData) GetNodePubKey() []byte {
	if x != nil {
		return x.NodePubKey
	}
	return nil
}

func (x *MessageData) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

type NeighborMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageData   *MessageData           `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeighborMessage) Reset() {
	*x = NeighborMessage{}
	mi := &file_pkg_proto_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeighborMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeighborMessage) ProtoMessage() {}

func (x *NeighborMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeighborMessage.ProtoReflect.Descriptor instead.
func (*NeighborMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_network_proto_rawDescGZIP(), []int{1}
}

func (x *NeighborMessage) GetMessageData() *MessageData {
	if x != nil {
		return x.MessageData
	}
	return nil
}

type NeighborMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageData   *MessageData           `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeighborMessageResponse) Reset() {
	*x = NeighborMessageResponse{}
	mi := &file_pkg_proto_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeighborMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeighborMessageResponse) ProtoMessage() {}

func (x *NeighborMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeighborMessageResponse.ProtoReflect.Descriptor instead.
func (*NeighborMessageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_network_proto_rawDescGZIP(), []int{2}
}

func (x *NeighborMessageResponse) GetMessageData() *MessageData {
	if x != nil {
		return x.MessageData
	}
	return nil
}

func (x *NeighborMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ProtocolMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageData   *MessageData           `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // serialized protobufs of the method specific data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolMessage) Reset() {
	*x = ProtocolMessage{}
	mi := &file_pkg_proto_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolMessage) ProtoMessage() {}

func (x *ProtocolMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolMessage.ProtoReflect.Descriptor instead.
func (*ProtocolMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_network_proto_rawDescGZIP(), []int{3}
}

func (x *ProtocolMessage) GetMessageData() *MessageData {
	if x != nil {
		return x.MessageData
	}
	return nil
}

func (x *ProtocolMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_pkg_proto_network_proto protoreflect.FileDescriptor

const file_pkg_proto_network_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/proto/network.proto\x12\x05proto\"\xc5\x01\n" +
	"\vMessageData\x12$\n" +
	"\rclientVersion\x18\x01 \x01(\tR\rclientVersion\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x16\n" +
	"\x06gossip\x18\x04 \x01(\bR\x06gossip\x12\x16\n" +
	"\x06nodeId\x18\x05 \x01(\tR\x06nodeId\x12\x1e\n" +
	"\n" +
	"nodePubKey\x18\x06 \x01(\fR\n" +
	"nodePubKey\x12\x12\n" +
	"\x04sign\x18\a \x01(\fR\x04sign\"G\n" +
	"\x0fNeighborMessage\x124\n" +
	"\vmessageData\x18\x01 \x01(\v2\x12.proto.MessageDataR\vmessageData\"i\n" +
	"\x17NeighborMessageResponse\x124\n" +
	"\vmessageData\x18\x01 \x01(\v2\x12.proto.MessageDataR\vmessageData\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"a\n" +
	"\x0fProtocolMessage\x124\n" +
	"\vmessageData\x18\x01 \x01(\v2\x12.proto.MessageDataR\vmessageData\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayloadB\x11Z\x0fcommittee/protob\x06proto3"

var (
	file_pkg_proto_network_proto_rawDescOnce sync.Once
	file_pkg_proto_network_proto_rawDescData []byte
)

func file_pkg_proto_network_proto_rawDescGZIP() []byte {
	file_pkg_proto_network_proto_rawDescOnce.Do(func() {
		file_pkg_proto_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_network_proto_rawDesc), len(file_pkg_proto_network_proto_rawDesc)))
	})
	return file_pkg_proto_network_proto_rawDescData
}

var file_pkg_proto_network_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_network_proto_goTypes = []any{
	(*MessageData)(nil),             // 0: proto.MessageData
	(*NeighborMessage)(nil),         // 1: proto.NeighborMessage
	(*NeighborMessageResponse)(nil), // 2: proto.NeighborMessageResponse
	(*ProtocolMessage)(nil),         // 3: proto.ProtocolMessage
}
var file_pkg_proto_network_proto_depIdxs = []int32{
	0, // 0: proto.NeighborMessage.messageData:type_name -> proto.MessageData
	0, // 1: proto.NeighborMessageResponse.messageData:type_name -> proto.MessageData
	0, // 2: proto.ProtocolMessage.messageData:type_name -> proto.MessageData
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_network_proto_init() }
func file_pkg_proto_network_proto_init() {
	if File_pkg_proto_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_network_proto_rawDesc), len(file_pkg_proto_network_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_network_proto_goTypes,
		DependencyIndexes: file_pkg_proto_network_proto_depIdxs,
		MessageInfos:      file_pkg_proto_network_proto_msgTypes,
	}.Build()
	File_pkg_proto_network_proto = out.File
	file_pkg_proto_network_proto_goTypes = nil
	file_pkg_proto_network_proto_depIdxs = nil
}
