// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: pkg/proto/timestamp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TimestampMessage represents a message in the ExAnte and ExPost protocols.
type TimestampMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session identifier for this protocol instance
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// The sender's verification key
	VerificationKey []byte `protobuf:"bytes,2,opt,name=verification_key,json=verificationKey,proto3" json:"verification_key,omitempty"`
	// The value associated with the verification key
	Value []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Auxiliary data
	Aux *Aux `protobuf:"bytes,4,opt,name=aux,proto3" json:"aux,omitempty"`
	// Merkle path
	MerklePath []*State `protobuf:"bytes,5,rep,name=merkle_path,json=merklePath,proto3" json:"merkle_path,omitempty"`
	// Round number
	Round uint32 `protobuf:"varint,6,opt,name=round,proto3" json:"round,omitempty"`
	// Identity of the sending node
	Id            string `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimestampMessage) Reset() {
	*x = TimestampMessage{}
	mi := &file_pkg_proto_timestamp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampMessage) ProtoMessage() {}

func (x *TimestampMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_timestamp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampMessage.ProtoReflect.Descriptor instead.
func (*TimestampMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_timestamp_proto_rawDescGZIP(), []int{0}
}

func (x *TimestampMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TimestampMessage) GetVerificationKey() []byte {
	if x != nil {
		return x.VerificationKey
	}
	return nil
}

func (x *TimestampMessage) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *TimestampMessage) GetAux() *Aux {
	if x != nil {
		return x.Aux
	}
	return nil
}

func (x *TimestampMessage) GetMerklePath() []*State {
	if x != nil {
		return x.MerklePath
	}
	return nil
}

func (x *TimestampMessage) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *TimestampMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           [][]byte               `protobuf:"bytes,1,rep,name=row,proto3" json:"row,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_pkg_proto_timestamp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_timestamp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_pkg_proto_timestamp_proto_rawDescGZIP(), []int{1}
}

func (x *State) GetRow() [][]byte {
	if x != nil {
		return x.Row
	}
	return nil
}

type Aux struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PiRP          []byte                 `protobuf:"bytes,1,opt,name=PiRP,proto3" json:"PiRP,omitempty"`
	AuxKey        *AuxKeyMessage         `protobuf:"bytes,2,opt,name=aux_key,json=auxKey,proto3" json:"aux_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Aux) Reset() {
	*x = Aux{}
	mi := &file_pkg_proto_timestamp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Aux) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Aux) ProtoMessage() {}

func (x *Aux) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_timestamp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Aux.ProtoReflect.Descriptor instead.
func (*Aux) Descriptor() ([]byte, []int) {
	return file_pkg_proto_timestamp_proto_rawDescGZIP(), []int{2}
}

func (x *Aux) GetPiRP() []byte {
	if x != nil {
		return x.PiRP
	}
	return nil
}

func (x *Aux) GetAuxKey() *AuxKeyMessage {
	if x != nil {
		return x.AuxKey
	}
	return nil
}

// AuxKeyMessage represents the auxiliary key data
type AuxKeyMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// VRF output
	PhiVrf []byte `protobuf:"bytes,1,opt,name=phi_vrf,json=phiVrf,proto3" json:"phi_vrf,omitempty"`
	// VRF proof
	PiVrf []byte `protobuf:"bytes,2,opt,name=pi_vrf,json=piVrf,proto3" json:"pi_vrf,omitempty"`
	// VDF output
	PhiVdf []byte `protobuf:"bytes,3,opt,name=phi_vdf,json=phiVdf,proto3" json:"phi_vdf,omitempty"`
	// VDF proof
	PiVdf         []byte `protobuf:"bytes,4,opt,name=pi_vdf,json=piVdf,proto3" json:"pi_vdf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuxKeyMessage) Reset() {
	*x = AuxKeyMessage{}
	mi := &file_pkg_proto_timestamp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuxKeyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuxKeyMessage) ProtoMessage() {}

func (x *AuxKeyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_timestamp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuxKeyMessage.ProtoReflect.Descriptor instead.
func (*AuxKeyMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_timestamp_proto_rawDescGZIP(), []int{3}
}

func (x *AuxKeyMessage) GetPhiVrf() []byte {
	if x != nil {
		return x.PhiVrf
	}
	return nil
}

func (x *AuxKeyMessage) GetPiVrf() []byte {
	if x != nil {
		return x.PiVrf
	}
	return nil
}

func (x *AuxKeyMessage) GetPhiVdf() []byte {
	if x != nil {
		return x.PhiVdf
	}
	return nil
}

func (x *AuxKeyMessage) GetPiVdf() []byte {
	if x != nil {
		return x.PiVdf
	}
	return nil
}

var File_pkg_proto_timestamp_proto protoreflect.FileDescriptor

var file_pkg_proto_timestamp_proto_rawDesc = string([]byte{
	0x0a, 0x19, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xe5, 0x01, 0x0a, 0x10, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x03, 0x61, 0x75, 0x78, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x75, 0x78,
	0x52, 0x03, 0x61, 0x75, 0x78, 0x12, 0x2d, 0x0a, 0x0b, 0x6d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x5f,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0a, 0x6d, 0x65, 0x72, 0x6b, 0x6c, 0x65,
	0x50, 0x61, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x19, 0x0a, 0x05, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x03, 0x72, 0x6f, 0x77, 0x22, 0x48, 0x0a, 0x03, 0x41, 0x75, 0x78, 0x12, 0x12, 0x0a, 0x04,
	0x50, 0x69, 0x52, 0x50, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x50, 0x69, 0x52, 0x50,
	0x12, 0x2d, 0x0a, 0x07, 0x61, 0x75, 0x78, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x75, 0x78, 0x4b, 0x65, 0x79,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x06, 0x61, 0x75, 0x78, 0x4b, 0x65, 0x79, 0x22,
	0x6f, 0x0a, 0x0d, 0x41, 0x75, 0x78, 0x4b, 0x65, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x70, 0x68, 0x69, 0x5f, 0x76, 0x72, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x70, 0x68, 0x69, 0x56, 0x72, 0x66, 0x12, 0x15, 0x0a, 0x06, 0x70, 0x69, 0x5f,
	0x76, 0x72, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x70, 0x69, 0x56, 0x72, 0x66,
	0x12, 0x17, 0x0a, 0x07, 0x70, 0x68, 0x69, 0x5f, 0x76, 0x64, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x70, 0x68, 0x69, 0x56, 0x64, 0x66, 0x12, 0x15, 0x0a, 0x06, 0x70, 0x69, 0x5f,
	0x76, 0x64, 0x66, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x70, 0x69, 0x56, 0x64, 0x66,
	0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d,
	0x61, 0x6d, 0x6f, 0x72, 0x73, 0x6b, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65,
	0x65, 0x2d, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_pkg_proto_timestamp_proto_rawDescOnce sync.Once
	file_pkg_proto_timestamp_proto_rawDescData []byte
)

func file_pkg_proto_timestamp_proto_rawDescGZIP() []byte {
	file_pkg_proto_timestamp_proto_rawDescOnce.Do(func() {
		file_pkg_proto_timestamp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_timestamp_proto_rawDesc), len(file_pkg_proto_timestamp_proto_rawDesc)))
	})
	return file_pkg_proto_timestamp_proto_rawDescData
}

var file_pkg_proto_timestamp_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_timestamp_proto_goTypes = []any{
	(*TimestampMessage)(nil), // 0: proto.TimestampMessage
	(*State)(nil),            // 1: proto.State
	(*Aux)(nil),              // 2: proto.Aux
	(*AuxKeyMessage)(nil),    // 3: proto.AuxKeyMessage
}
var file_pkg_proto_timestamp_proto_depIdxs = []int32{
	2, // 0: proto.TimestampMessage.aux:type_name -> proto.Aux
	1, // 1: proto.TimestampMessage.merkle_path:type_name -> proto.State
	3, // 2: proto.Aux.aux_key:type_name -> proto.AuxKeyMessage
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_timestamp_proto_init() }
func file_pkg_proto_timestamp_proto_init() {
	if File_pkg_proto_timestamp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_timestamp_proto_rawDesc), len(file_pkg_proto_timestamp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_timestamp_proto_goTypes,
		DependencyIndexes: file_pkg_proto_timestamp_proto_depIdxs,
		MessageInfos:      file_pkg_proto_timestamp_proto_msgTypes,
	}.Build()
	File_pkg_proto_timestamp_proto = out.File
	file_pkg_proto_timestamp_proto_goTypes = nil
	file_pkg_proto_timestamp_proto_depIdxs = nil
}
